@startuml
hide footbox
->":AddCommand":execute(data, ui)
activate ":AddCommand"
":AddCommand" -> ":AddCommand": updateAmount()
activate ":AddCommand"
":AddCommand" --> ":AddCommand"
deactivate ":AddCommand"
":AddCommand" -> ":AddCommand": updateCurrency()
activate ":AddCommand"
":AddCommand" --> ":AddCommand"
deactivate ":AddCommand"
":AddCommand" -> ":SpendingList": addItem(description,\ncurrency, amount)
activate ":SpendingList"
":SpendingList" --> ":AddCommand"
deactivate ":SpendingList"
":AddCommand" -> ":Ui": printAdd(spendingList)
activate ":Ui"
":Ui" --> ":AddCommand"
deactivate ":Ui"
opt size > 1
":AddCommand" -> ":SpendingListCategoriser": execute(spendingList)
activate ":SpendingListCategoriser"
":SpendingListCategoriser" --> ":AddCommand"
deactivate ":SpendingListCategoriser"
end
opt size%8==0
":AddCommand" -> ":EncouragementCommand": execute(spendingList)
activate ":EncouragementCommand"
":EncouragementCommand" --> ":AddCommand"
deactivate ":EncouragementCommand"
end
opt Budget.hasBudget
":AddCommand" -> ":WarnCommand": execute(spendingList, null, ui)
activate ":WarnCommand"
":WarnCommand" --> ":AddCommand"
deactivate ":WarnCommand"
end
@enduml