@startuml
hide footbox

-> ":SummaryCommand": execute(spendingList, repaymentList, ui)
activate ":SummaryCommand"

":SummaryCommand" -> ":SpendingList": getSpendingAmount(period)
activate ":SpendingList"

loop spendingList.size() times


":SpendingList" -> ":Item": getDate()
activate ":Item"
":Item" --> ":SpendingList": date
deactivate ":Item"

opt period == date
":SpendingList" -> ":Item": getAmount()
activate ":Item"
":Item" --> ":SpendingList": amount
deactivate ":Item"

end

end

":SpendingList" --> ":SummaryCommand": amountSpent
deactivate ":SpendingList"
":SummaryCommand" -> ":Ui" : printSummaryMessage(amountSpent)
activate ":Ui"
":Ui" --> ":SummaryCommand"
deactivate ":Ui"

loop each category item
":SummaryCommand" -> ":SpendingList": getSpendingAmountCategory(period, category)
activate ":SpendingList"

loop spendingList.size() times
":SpendingList" -> ":Item": getDate()
activate ":Item"
":Item" --> ":SpendingList": date
deactivate ":Item"

":SpendingList" -> ":Item": getCategory()
activate ":Item"
":Item" --> ":SpendingList": category
deactivate ":Item"

opt period == date && c.toString() == category
":SpendingList" -> ":Item": getAmount()
activate ":Item"
":Item" --> ":SpendingList": amount
deactivate ":Item"
end
end


":SpendingList" --> ":SummaryCommand": amountSpent
deactivate ":SpendingList"

":SummaryCommand" -> ":Ui" : printSummaryCategory(amountSpent)
activate ":Ui"
":Ui" --> ":SummaryCommand"
deactivate ":Ui"
end

<-- ":SummaryCommand"
deactivate ":SummaryCommand"
@enduml