@startuml
 :User: as user        #tan
user<-right->(ui)
(main)-left->(ui)
(main)-->(command)
(command)-right->(data)
(main)-->(data)
(main)-right->(parser)
(data)-right->(storage)
(command)-->(ui)

@enduml