@startuml
package "Command" <<Rectangle>> {
abstract class Command {
+execute() {abstract}:void
+isExit():boolean
}
package "User Command" <<Rectangle>> {
AddCommand -[hidden]up-|> Command
ClearBudgetCommand -[hidden]up-|> Command
ClearListCommand -[hidden]up-> Command
ConvertCommand -[hidden]up-> AddCommand
EditCommand -[hidden]up-> ClearBudgetCommand
ExitCommand -[hidden]up-> ClearListCommand
ExportCommand -[hidden]up-> ConvertCommand
HelpCommand -[hidden]up-> EditCommand
ListCommand -[hidden]up-> ExitCommand
PurgeDataCommand -[hidden]up-> ExportCommand
RepayCommand -[hidden]up-> HelpCommand
SetBudgetCommand -[hidden]up-> ListCommand
SummaryCommand -[hidden]up-> PurgeDataCommand
ViewCommand -[hidden]up-> RepayCommand
}
package "System-issued Command" <<Rectangle>> {
EncouragementCommand -[hidden]up-|> SummaryCommand
WarnCommand -[hidden]up-|> ViewCommand
}
"System-issued Command" -[hidden]left|> "User Command"
"User Command"-up|> Command
"System-issued Command"-up|> Command
}
@enduml