@startuml
->":EditCommand":execute(spendingList, ui)
activate ":EditCommand"
":EditCommand"->":SpendingList":editItem(index, description, symbol, amount, category)
activate ":SpendingList"
":SpendingList"-->":EditCommand":
deactivate ":SpendingList"
":EditCommand"->":Ui":printEdit(spendingList, index)
activate ":Ui"
":Ui"-->":EditCommand":
deactivate ":Ui"
<--":EditCommand"
deactivate ":EditCommand"
@enduml