@startuml
->":EditCommand":execute(spendingList, ui)
activate ":EditCommand"
alt isDescription
":EditCommand"->":SpendingList":editItemDescription(index, description)
activate ":SpendingList"
":SpendingList"-->":EditCommand":
deactivate ":SpendingList"
else isCategory
":EditCommand"->":SpendingList":editItemCategory(index, description)
activate ":SpendingList"
":SpendingList"-->":EditCommand":
deactivate ":SpendingList"
else isAmount
":EditCommand"->":SpendingList":editItemAmount(index, amount)
activate ":SpendingList"
":SpendingList"-->":EditCommand":
deactivate ":SpendingList"
end
":EditCommand"->":Ui":printEdit(spendingList, index)
activate ":Ui"
":Ui"-->":EditCommand":
deactivate ":Ui"
<--":EditCommand"
deactivate ":EditCommand"
@enduml