@startuml
hide footbox

":Duke" -> ":Reminder"
create ":Reminder"
":Duke" -> ":Reminder"
activate ":Reminder"

":Reminder" -> ":Reminder" : saveDatesToList()
activate ":Reminder"
":Reminder" --> ":Reminder"
deactivate ":Reminder"
":Reminder" --> ":Duke"
deactivate ":Reminder"


->":Reminder" : execute(spendingList, ui)

activate ":Reminder"

opt Budget.hasBudget
":Reminder" -> ":WarnCommand" : execute(spendingList, ui)
activate ":WarnCommand"
":WarnCommand" --> ":Reminder"
deactivate ":WarnCommand"
end

loop week.size() times

":Reminder" -> ":SpendingList" : getSpendingAmountTime(period)
activate ":SpendingList"
":SpendingList" --> ":Reminder" : amountSpent
deactivate ":SpendingList"

end

":Reminder" -> ":Reminder" : findRemainingAmount(spendingList)
activate ":Reminder"
":Reminder" --> ":Reminder" : amountRemained
deactivate ":Reminder"


":Reminder" -> ":Ui" : printReminderMessage(totalAmountSpent,amountRemained,startWeek.toString())
activate ":Ui"
":Ui" --> ":Reminder"
deactivate ":Ui"
<-- ":Reminder"
deactivate ":Reminder"

@enduml