@startuml

hide circle
hide members
skinparam classAttributeIconSize 0

class "{abstract}\nCommand"
class RepaymentList
class Repay

RepaymentList *--> "0 .. *" Repay
"{abstract}\nCommand" -right-> RepaymentList : execute
RepaymentList ..> Storage
Storage -> RepaymentList

@enduml